version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: contacts_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_URL=postgresql+asyncpg://postgres:123456@postgres:5432/contacts_app
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  postgres-data: 
  redis-data: 